# Generated by Django 6.0.1 on 2026-01-17 02:23

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Si la aplicación está disponible en el sistema', verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Aplicación',
                'verbose_name_plural': 'Aplicaciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SharedFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('path', models.CharField(help_text='Ruta virtual de la carpeta (ej: /volume1/homes)', max_length=255, verbose_name='Ruta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Carpeta compartida',
                'verbose_name_plural': 'Carpetas compartidas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ej: volume1, volume2', max_length=100, unique=True, verbose_name='Nombre')),
                ('total_space', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Espacio total (GB)')),
                ('available_space', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Espacio disponible (GB)')),
            ],
            options={
                'verbose_name': 'Volumen',
                'verbose_name_plural': 'Volúmenes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre único del grupo', max_length=100, unique=True, verbose_name='Nombre del grupo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('folder_permissions', models.JSONField(blank=True, default=dict, help_text='Formato: {"folder_id": "rw|ro|na"} (rw=read-write, ro=read-only, na=no-access)', verbose_name='Permisos de carpetas')),
                ('quotas', models.JSONField(blank=True, default=dict, help_text='Formato: {"volume_id": {"amount": 100, "unit": "GB"}}', verbose_name='Cuotas')),
                ('app_permissions', models.JSONField(blank=True, default=dict, help_text='Formato: {"app_name": "allow|deny"}', verbose_name='Permisos de aplicaciones')),
                ('speed_limits', models.JSONField(blank=True, default=dict, help_text='Formato: {"service": {"upload": 100, "download": 200}} (KB/s)', verbose_name='Límites de velocidad')),
                ('is_system', models.BooleanField(default=False, help_text='Los grupos del sistema no se pueden eliminar', verbose_name='Grupo del sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('members', models.ManyToManyField(blank=True, related_name='groups_membership', to=settings.AUTH_USER_MODEL, verbose_name='Miembros')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['name'],
            },
        ),
    ]
