# Generated by Django 6.0.1 on 2026-01-16 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NASConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='IP o dominio del NAS (ej: 192.168.1.100 o nas.ejemplo.com)', max_length=255, verbose_name='Host')),
                ('port', models.PositiveIntegerField(default=5000, help_text='Puerto DSM (por defecto 5000 HTTP, 5001 HTTPS)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='Puerto')),
                ('protocol', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS (Seguro)')], default='https', max_length=5, verbose_name='Protocolo')),
                ('admin_username', models.CharField(help_text='Usuario con permisos de administrador en el NAS', max_length=100, verbose_name='Usuario Administrador')),
                ('admin_password', models.CharField(help_text='Contraseña del usuario administrador', max_length=255, verbose_name='Contraseña')),
                ('is_active', models.BooleanField(default=True, help_text='Solo puede haber una configuración activa', verbose_name='Configuración Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Configuración NAS',
                'verbose_name_plural': 'Configuraciones NAS',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
